name: Publish Longhorn PHP Open CFP Docker Image
on:
  push:
    branches:
      - conf-specific
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ord.vultrcr.com
          username: ${{ vars.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: mode=max
          tags: ord.vultrcr.com/longhorn/cfp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./docker/Dockerfile
          context: .
